### ISSUE TITLE
Problem Compiling in OS X

### ISSUE THREAD

**Issue by nimamox** [sin0emp/SpikeNN#1]
Hey,
I guess I've solved the problem I had with boost but there is still a problem in the last stage of make. It seems that the getPre/PostNeuronID() methods of class Synapse, which have apparently been added in the last commit, can not be accessed from IzhikevichDAHandler::setSynapse().
Oh and it compiles in Linux perfectly and I just see this in OSX with gcc-4.9!

nima@macbook:~/SpikeNN/build$ make
Scanning dependencies of target SpikeNN
...
[100%] Building CXX object CMakeFiles/SpikeNN.dir/src/DAHandler.cpp.o
Linking CXX shared library libSpikeNN.dylib
Undefined symbols for architecture x86_64:
  "Synapse::getPreNeuronID() const", referenced from:
      IzhikevichDAHandler::setSynapse(Synapse const_)  in DAHandler.cpp.o
  "Synapse::getPostNeuronID() const", referenced from:
      IzhikevichDAHandler::setSynapse(Synapse const_)  in DAHandler.cpp.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: **\* [libSpikeNN.dylib] Error 1
make[1]: **\* [CMakeFiles/SpikeNN.dir/all] Error 2
make: **\* [all] Error 2

**Comment by nimamox** [comment]
I fixed this problem by removing the 'inline' directive from the definitions of those methods. The directive only concerns the linker not the compiler and somehow ld fails with this on OS X. As this directive is outdated and irrelevant nowadays, you may want to modify this in the upstream repository as well.

**Comment by sin0emp** [comment]
Hey,That's odd, why is that a problem in OS X? I used 'inline' for those methods because I wanted to force them to be inline, as they will be called frequently. I get that code optimization processes will probably detect such things, but I didn't want to push my luck! Anyway, thanks for the report I will emit those directives in the next commit. Or if you want to advance things together, I'll make a branch for you in the repository.

REGARDS
PS: If you solved the problem you had with boost, can you fix that on Dr. Tabesh's laptop too? 

```
 On Monday, April 27, 2015 3:10 PM, nimamox <notifications@github.com> wrote:
```

 I fixed this problem by removing the 'inline' directive from the definitions of those methods. The directive only concerns the linker not the compiler and somehow ld fails with this on OS X. As this directive is outdated and irrelevant nowadays, you may want to modify this.—

**Comment by nimamox** [comment]
Hmmm, I do know that the body of an inline function needs to be in the header file so that it can be replaced as required. That is why Synapse::getDelay(), unlike getPre/PostNeuronID(), does not result in an error message. Still curious as to why it doesn't cause an error on other platforms, but my guess is that they default to different C++ standards.

https://gcc.gnu.org/onlinedocs/gcc/Inline.html

As for the branch, thanks, but I'm still learning and trying to get my hands dirty with your library and I'm not sure if I can have any contribution in near future. Though I certainly appreciate the gesture :)
